# Generated by Django 4.2.7 on 2023-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'verbose_name': 'APIKey',
                'verbose_name_plural': 'APIKeys',
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pill_api.apikey')),
            ],
            options={
                'verbose_name': 'APILog',
                'verbose_name_plural': 'APILogs',
            },
        ),
    ]
