# Generated by Django 4.2.7 on 2023-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RxName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'RxName',
                'verbose_name_plural': 'RxName',
            },
        ),
        migrations.CreateModel(
            name='RxPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndc', models.CharField(db_index=True, max_length=16)),
                ('drug_data', models.TextField()),
                ('dea_classification', models.CharField(blank=True, max_length=16, null=True)),
                ('gsdb_item_id', models.IntegerField(db_index=True)),
                ('gsdb_item_version', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsdb_datalab.rxname')),
            ],
            options={
                'verbose_name': 'RxPill',
                'verbose_name_plural': 'RxPills',
            },
        ),
        migrations.CreateModel(
            name='RxPillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsdb_image_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_image_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('rxpill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gsdb_datalab.rxpill')),
            ],
            options={
                'verbose_name': 'RxPillImage',
                'verbose_name_plural': 'RxPillImages',
            },
        ),
    ]
